services:
  psql:
    image: postgres:16
    container_name: postgresql_database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - "${DB_PORT}:5432" 
    volumes:
    - psql_volume:/var/lib/postgresql/data
  
  # server: 
  #   image:
  #     build:
  
  # client:
  #   image:
  #     build:

volumes:
  psql_volume:
